# Generated by Django 5.0.7 on 2024-08-10 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_about_backgraund'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='name')),
                ('intergers', models.CharField(max_length=256, verbose_name='intergers')),
            ],
        ),
    ]
